# Generated by Django 2.2.7 on 2020-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=200)),
                ('crawling_url', models.URLField(max_length=300)),
                ('input_col', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_word', models.CharField(max_length=255)),
                ('active_status', models.IntegerField()),
                ('executed_date', models.DateField()),
                ('complited_date', models.DateField()),
                ('t_st_date', models.DateField()),
                ('t_end_date', models.DateField()),
                ('media', models.ForeignKey(on_delete=True, to='Jobs.Target_list')),
            ],
        ),
    ]
