# Generated by Django 2.2.7 on 2020-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_word', models.CharField(max_length=255)),
                ('media', models.CharField(max_length=200)),
                ('active_status', models.IntegerField()),
                ('executed_date', models.DateField()),
                ('complited_date', models.DateField()),
                ('t_st_date', models.DateField()),
                ('t_end_date', models.DateField()),
            ],
        ),
    ]
