# Generated by Django 2.2.7 on 2020-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=200)),
                ('crawling_url', models.URLField(max_length=300)),
                ('input_col', models.TextField()),
            ],
        ),
    ]
