# Generated by Django 2.2.7 on 2020-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_target_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='media',
            field=models.ForeignKey(on_delete=True, to='Jobs.Target_list'),
        ),
    ]
